### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by erichlf** [julian-alarcon/prospect-mail#315]
**Describe the bug**
When signing in using 2FA I get the following:
```
UTC Date: 2023-11-20T07:24:31.712Z
Client Id: EC698FA855AD45248B3397D4606CB7D9
Session Id: cee27491-9843-4f81-9541-bcb7059bf70c
Client Version: 20231110003.11
BootResult: configuration
Back Filled Errors: Unhandled Rejection: Error: 500:undefined|undefined:undefined
err: Microsoft.Exchange.Clients.Owa2.Server.Core.OwaUserHasNoMailboxAndNoLicenseAssignedException
esrc: StartupData
et: ServerError
estack: Error: 500
    at Object.s [as createStatusErrorMessage] (https://res.cdn.office.net/owamail/hashed-v1/scripts/owa.mailindex.8b0d6632.js:2:80223)
    at https://res.cdn.office.net/owamail/hashed-v1/scripts/owa.mailindex.8b0d6632.js:2:93379
st: 500
ehk: X-OWA-Error
efe: AM6P193CA0094, FRYP281CA0007
ebe: AS8PR09MB5256
emsg: UserHasNoMailboxAndNoLicenseAssignedError
```
I've have seen bug reports like this before and the suggestion has always been to use a different version. These suggestions have not helped me.

**To Reproduce**

1. After installing open prospect-mail for the first time.
2. Use my university email at sign-in, which redirects me to the university sign-in page
3. Sign in as per usual
4. I get a notification to verify sign in on my phone
5. Verify sign in on my phone
6. Receive error

**Expected behavior**
I expect that step 6 above has me signed in on prospect-mail.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.3
- Installation source: snap beta channel
- Version: 0.5.3

**Additional context**
I have tried may builds and haven't successfully signed in once.

**Comment by julian-alarcon** [comment]
Can you provide a screenshot with the error?

Also, please test the latest release, I made multiple changes to how the application works:
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.6.0-beta1
