### ISSUE TITLE
[Bug]: Login screen must fully support HTML5 and local storage features.

### ISSUE THREAD

**Issue by qtlin** [julian-alarcon/prospect-mail#337]
Please see evolution-data-server https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/515 for all details.

**Comment by qtlin** [comment]
the above-mentioned evolution ticket has been very active recently, since another problem encountered since original message. have you tried to read it? I believe it contains sufficient information.

**Comment by qtlin** [comment]
0.6.1 beta rpm package on RHEL 9 derivative:
```
$ /usr/bin/prospect-mail 

(process:76940): Gtk-ERROR **: 13:51:26.481: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
Trace/BPT trap (core dumped)
$
```

**Comment by julian-alarcon** [comment]
The last log error may not be related with your issue.

Can you take a look at the console tab opening prospect-mail with the NODE_ENV, in a terminal like this?
`NODE_ENV=development prospect-mail`

**Comment by qtlin** [comment]
0.5.x doesn't crash, while 0.6.x crashes. However, crash aside, have you read the evolution ticket mentioned? It clearly says what part of HTTP protocol(s) is(are) missing on the client. Must be trivial to enable.
I would prefer avoid mixing 0.5 and 0.6 problems here, but your suggestion to produce more output did not help.
```
$ env NODE_ENV=development prospect-mail

(process:15547): Gtk-ERROR **: 19:05:23.212: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
Trace/BPT trap (core dumped)
$
```
the crash is
(gdb) where
```
#0  0x00007ffff7affde2 in g_log_writer_default () at /lib64/libglib-2.0.so.0
#1  0x00007ffff7afa694 in g_log_structured_array () at /lib64/libglib-2.0.so.0
#2  0x00007ffff7afa8e8 in g_log_structured_standard () at /lib64/libglib-2.0.so.0
#3  0x00007fff576fdd1b in gtk_init_check () at /lib64/libgtk-4.so.1
```

above GTK error message seems definitely related to the crash.

**Comment by julian-alarcon** [comment]
I'm sorry, it is not clear from the initial description, so you have 2 errors, a blank screen and a crash?

**Comment by qtlin** [comment]
Thank you for providing a workaround. With above command 0.6 beta works and blank screen login page is no longer reproducible. Problem solved.
